# syntax=docker/dockerfile:1.19.0

# GPU Test Container for Cloud Run Jobs
# Uses NVIDIA L4 GPU with CUDA 12.2

FROM python:3.13-slim-trixie
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \ 
    apt update && apt install -y sccache rustup build-essential

RUN --mount=type=cache,target=/root/.cache/cargo \
    --mount=type=cache,target=/root/.cache/rustup \
    rustup default stable

WORKDIR /app

RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --frozen --no-install-workspace --extra cuda12 -p 3.13


# Set environment variables
ENV JAX_ENABLE_X64=1
ENV JAX_PLATFORMS=cuda,cpu
ENV RUSTC_WRAPPER=sccache
ENV SCCACHE_DIR=/root/.cache/sccache

COPY --exclude=.git* --exclude=.venv* --exclude=*/.venv --exclude=.p* --exclude="Dockerfile*"  . /app

RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=cache,target=/root/.cache/sccache \
    --mount=type=cache,target=/root/.cache/cargo \
    --mount=type=cache,target=/root/.cache/rustup \
    uv sync --locked --extra cuda12

# The CI workflow will clone the repo and pip install before running tests
ENTRYPOINT ["/bin/bash", "-c"]
